apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: registered-thrush-nodejs 
  janus-idp.io/tekton: registered-thrush-nodejs
  backstage.io/kubernetes-id: registered-thrush-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: registered-thrush-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  