apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: registered-thrush-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: registered-thrush-nodejs 
  name: registered-thrush-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: registered-thrush-nodejs 
