apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: registered-thrush-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:769abe5181cb4f7b71a9cf0caa346d094cb81ca2@sha256:76ef3c4fa82833fd6079e4bfa61029bcaf29e4fd084b083f8af9266424edb5fa
          name: container-image
